exclude: ['README.md', 'project.md', 'lin10.md', 'stack-decoder', 'hw0.md', 'hw3.md', 'hw4.md', 'hw5.md', 'hw-writing-exercise.md']
timezone: GMT
markdown: kramdown
destination: ../inf-mt
encoding: ASCII-8BIT
defaults:
  -
    values:
      layout: "informatics"
